language: r
sudo: true
before_install:
  - sudo apt-get update
  - sudo apt-get -y install openjdk-8-jre
  - sudo apt-get -y install r-cran-rjava
  - sudo R CMD javareconf

cache: packages
warnings_are_errors: true
matrix:
  include:
    - os:
      - linux
    r:
      #- oldrel
      - release
      #- devel
r_packages:
  - covr
after_success:
  - R -q -e 'library("covr");codecov()'